version: '3'

networks:
  my-net:
services:
  mongo-database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - my-net
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo-database:27017/post-clean-code
      - REDIS_URL=redis://redis-database:6379
    depends_on:
      - mongo-database
    networks:
      - my-net
